version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: devops-postgres
    restart: always
    environment:
      POSTGRES_DB: devops_project_db
      POSTGRES_USER: shubh_user
      POSTGRES_PASSWORD: shubh_secure_password_2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - devops-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shubh_user -d devops_project_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devops-backend
    restart: always
    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shubh_user
      DB_PASSWORD: shubh_secure_password_2026
      DB_NAME: devops_project_db
      STUDENT_NAME: "Shubh Shukla"
      STUDENT_ID: "24bcs10093"
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - devops-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devops-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
